title:              Data Lab
email:              vyinghope90@gmail.com
description:        Tips, Tricks and Tutorials for Tech Community and Cyber-Security
author:             Charles Shaju
baseurl:            ""
url:                "https://Mr___CS.github.io"

# Social Profiles
twitter_username:   https://twitter.com/Mr___CS
github_username:    Charles-Shaju
facebook_username:  
instagram_username:  
linkedin_username:   https://linkedin.com/charles-shaju

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
highlighter: rouge